version: 2
updates:
  - package-ecosystem: "pip" # Confusingly, pip is correct for poetry
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      all-dependencies:
        patterns:
          - "*"
