version: 2
updates:
  - package-ecosystem: "pip" # Dependabot uses pip for uv-managed pyproject files
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "mlflow"
        versions: [">= 3.8"]
    groups:
      all-dependencies:
        patterns:
          - "*"
