# Edit this file to add your secrets.

# This is an example of how to define a secret.
# The config is saying that within scope "vllm" we have a
# key named "api_key" that we are setting to value "changeme".
[vllm]
api_key = "changeme"

# Here are some commonly needed keys you can uncomment and use.
[together]
# api_key = "fake key"

[perspective_api]
# api_key = "<your key here>"
