name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cli-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Start MLflow server (no jupyter)
        run: |
          ./start_services.sh no-jupyter

      - name: Install poetry
        run: pipx install "poetry == 1.8.5"

      - name: Install dependencies
        run: poetry install --with test --no-cache

      - name: Run all tests
        run: MLFLOW_TRACKING_URI=http://localhost:8080 poetry run pytest

      - name: Stop MLflow server
        run: docker compose down

  jupyter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Start MLflow server
        run: |
          ./start_services.sh

      - name: Copy test script to Jupyter container
        run: |
          docker cp tests/notebooks/run.py jupyter:/app/test_notebooks.py

      - name: Execute all notebooks
        run: |
          docker exec jupyter python /app/test_notebooks.py

          
      - name: Stop MLflow server
        run: docker compose down
